# Generated by Django 2.2.4 on 2019-08-28 16:30

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[(products.models.StatusChoice('Ready'), 'Ready'), (products.models.StatusChoice('Soldout'), 'Soldout')], max_length=10),
        ),
    ]
