# Generated by Django 2.2.4 on 2019-08-31 12:47

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status2',
            field=models.CharField(blank=True, choices=[(products.models.StatusChoice('Ready'), 'Ready'), (products.models.StatusChoice('Soldout'), 'Soldout')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Ready', 'Ready'), ('Soldout', 'Soldout')], default='Ready', max_length=10),
        ),
    ]
