# Generated by Django 2.2.4 on 2019-08-31 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190831_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status2',
        ),
    ]
